### ISSUE TITLE
Hello, thank you very much for sharing the code, can you tell me the source of the method?

### ISSUE THREAD

**Issue by WZYZSKMM** [jyh2012/photometric-stereo-with-unknown-lighting#1]
Hello, thank you very much for sharing this code, can you tell me the source of the method?

**Comment by jyh2012** [comment]
> Hello, thank you very much for sharing this code, can you tell me the source of the method?

Hello，i'm referencing by this https://github.com/xiumingzhang/photometric-stereo.git
